/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOrganisationsRouteImport } from './routes/_app/organisations'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppOrganisationsIndexRouteImport } from './routes/_app/organisations/index'
import { Route as AppSettingsGeneralRouteImport } from './routes/_app/settings/general'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppOrganisationsOrganisationIdRouteImport } from './routes/_app/organisations/$organisationId'
import { Route as AppOrganisationsOrganisationIdIndexRouteImport } from './routes/_app/organisations/$organisationId/index'
import { Route as AppOrganisationsOrganisationIdSettingsRouteImport } from './routes/_app/organisations/$organisationId/settings'
import { Route as AppOrganisationsOrganisationIdOverviewRouteImport } from './routes/_app/organisations/$organisationId/overview'
import { Route as AppOrganisationsOrganisationIdMembersRouteImport } from './routes/_app/organisations/$organisationId/members'
import { Route as AppOrganisationsOrganisationIdEventsIndexRouteImport } from './routes/_app/organisations/$organisationId/events/index'
import { Route as AppOrganisationsOrganisationIdBoardsIndexRouteImport } from './routes/_app/organisations/$organisationId/boards/index'
import { Route as AppOrganisationsOrganisationIdEventsEventIdRouteImport } from './routes/_app/organisations/$organisationId/events/$eventId'
import { Route as AppOrganisationsOrganisationIdBoardsBoardIdRouteImport } from './routes/_app/organisations/$organisationId/boards/$boardId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationsRoute = AppOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppOrganisationsIndexRoute = AppOrganisationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganisationsRoute,
} as any)
const AppSettingsGeneralRoute = AppSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppOrganisationsOrganisationIdRoute =
  AppOrganisationsOrganisationIdRouteImport.update({
    id: '/$organisationId',
    path: '/$organisationId',
    getParentRoute: () => AppOrganisationsRoute,
  } as any)
const AppOrganisationsOrganisationIdIndexRoute =
  AppOrganisationsOrganisationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdSettingsRoute =
  AppOrganisationsOrganisationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdOverviewRoute =
  AppOrganisationsOrganisationIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdMembersRoute =
  AppOrganisationsOrganisationIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdEventsIndexRoute =
  AppOrganisationsOrganisationIdEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdBoardsIndexRoute =
  AppOrganisationsOrganisationIdBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdEventsEventIdRoute =
  AppOrganisationsOrganisationIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)
const AppOrganisationsOrganisationIdBoardsBoardIdRoute =
  AppOrganisationsOrganisationIdBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => AppOrganisationsOrganisationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/organisations': typeof AppOrganisationsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/organisations/$organisationId': typeof AppOrganisationsOrganisationIdRouteWithChildren
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/organisations/': typeof AppOrganisationsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/organisations/$organisationId/members': typeof AppOrganisationsOrganisationIdMembersRoute
  '/organisations/$organisationId/overview': typeof AppOrganisationsOrganisationIdOverviewRoute
  '/organisations/$organisationId/settings': typeof AppOrganisationsOrganisationIdSettingsRoute
  '/organisations/$organisationId/': typeof AppOrganisationsOrganisationIdIndexRoute
  '/organisations/$organisationId/boards/$boardId': typeof AppOrganisationsOrganisationIdBoardsBoardIdRoute
  '/organisations/$organisationId/events/$eventId': typeof AppOrganisationsOrganisationIdEventsEventIdRoute
  '/organisations/$organisationId/boards': typeof AppOrganisationsOrganisationIdBoardsIndexRoute
  '/organisations/$organisationId/events': typeof AppOrganisationsOrganisationIdEventsIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/general': typeof AppSettingsGeneralRoute
  '/organisations': typeof AppOrganisationsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/organisations/$organisationId/members': typeof AppOrganisationsOrganisationIdMembersRoute
  '/organisations/$organisationId/overview': typeof AppOrganisationsOrganisationIdOverviewRoute
  '/organisations/$organisationId/settings': typeof AppOrganisationsOrganisationIdSettingsRoute
  '/organisations/$organisationId': typeof AppOrganisationsOrganisationIdIndexRoute
  '/organisations/$organisationId/boards/$boardId': typeof AppOrganisationsOrganisationIdBoardsBoardIdRoute
  '/organisations/$organisationId/events/$eventId': typeof AppOrganisationsOrganisationIdEventsEventIdRoute
  '/organisations/$organisationId/boards': typeof AppOrganisationsOrganisationIdBoardsIndexRoute
  '/organisations/$organisationId/events': typeof AppOrganisationsOrganisationIdEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/organisations': typeof AppOrganisationsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/organisations/$organisationId': typeof AppOrganisationsOrganisationIdRouteWithChildren
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/general': typeof AppSettingsGeneralRoute
  '/_app/organisations/': typeof AppOrganisationsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/organisations/$organisationId/members': typeof AppOrganisationsOrganisationIdMembersRoute
  '/_app/organisations/$organisationId/overview': typeof AppOrganisationsOrganisationIdOverviewRoute
  '/_app/organisations/$organisationId/settings': typeof AppOrganisationsOrganisationIdSettingsRoute
  '/_app/organisations/$organisationId/': typeof AppOrganisationsOrganisationIdIndexRoute
  '/_app/organisations/$organisationId/boards/$boardId': typeof AppOrganisationsOrganisationIdBoardsBoardIdRoute
  '/_app/organisations/$organisationId/events/$eventId': typeof AppOrganisationsOrganisationIdEventsEventIdRoute
  '/_app/organisations/$organisationId/boards/': typeof AppOrganisationsOrganisationIdBoardsIndexRoute
  '/_app/organisations/$organisationId/events/': typeof AppOrganisationsOrganisationIdEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/organisations'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/'
    | '/organisations/$organisationId'
    | '/settings/account'
    | '/settings/general'
    | '/organisations/'
    | '/settings/'
    | '/organisations/$organisationId/members'
    | '/organisations/$organisationId/overview'
    | '/organisations/$organisationId/settings'
    | '/organisations/$organisationId/'
    | '/organisations/$organisationId/boards/$boardId'
    | '/organisations/$organisationId/events/$eventId'
    | '/organisations/$organisationId/boards'
    | '/organisations/$organisationId/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signup'
    | '/'
    | '/settings/account'
    | '/settings/general'
    | '/organisations'
    | '/settings'
    | '/organisations/$organisationId/members'
    | '/organisations/$organisationId/overview'
    | '/organisations/$organisationId/settings'
    | '/organisations/$organisationId'
    | '/organisations/$organisationId/boards/$boardId'
    | '/organisations/$organisationId/events/$eventId'
    | '/organisations/$organisationId/boards'
    | '/organisations/$organisationId/events'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/organisations'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/organisations/$organisationId'
    | '/_app/settings/account'
    | '/_app/settings/general'
    | '/_app/organisations/'
    | '/_app/settings/'
    | '/_app/organisations/$organisationId/members'
    | '/_app/organisations/$organisationId/overview'
    | '/_app/organisations/$organisationId/settings'
    | '/_app/organisations/$organisationId/'
    | '/_app/organisations/$organisationId/boards/$boardId'
    | '/_app/organisations/$organisationId/events/$eventId'
    | '/_app/organisations/$organisationId/boards/'
    | '/_app/organisations/$organisationId/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisations': {
      id: '/_app/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof AppOrganisationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/organisations/': {
      id: '/_app/organisations/'
      path: '/'
      fullPath: '/organisations/'
      preLoaderRoute: typeof AppOrganisationsIndexRouteImport
      parentRoute: typeof AppOrganisationsRoute
    }
    '/_app/settings/general': {
      id: '/_app/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AppSettingsGeneralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/organisations/$organisationId': {
      id: '/_app/organisations/$organisationId'
      path: '/$organisationId'
      fullPath: '/organisations/$organisationId'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdRouteImport
      parentRoute: typeof AppOrganisationsRoute
    }
    '/_app/organisations/$organisationId/': {
      id: '/_app/organisations/$organisationId/'
      path: '/'
      fullPath: '/organisations/$organisationId/'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdIndexRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/settings': {
      id: '/_app/organisations/$organisationId/settings'
      path: '/settings'
      fullPath: '/organisations/$organisationId/settings'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdSettingsRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/overview': {
      id: '/_app/organisations/$organisationId/overview'
      path: '/overview'
      fullPath: '/organisations/$organisationId/overview'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdOverviewRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/members': {
      id: '/_app/organisations/$organisationId/members'
      path: '/members'
      fullPath: '/organisations/$organisationId/members'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdMembersRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/events/': {
      id: '/_app/organisations/$organisationId/events/'
      path: '/events'
      fullPath: '/organisations/$organisationId/events'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdEventsIndexRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/boards/': {
      id: '/_app/organisations/$organisationId/boards/'
      path: '/boards'
      fullPath: '/organisations/$organisationId/boards'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdBoardsIndexRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/events/$eventId': {
      id: '/_app/organisations/$organisationId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/organisations/$organisationId/events/$eventId'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdEventsEventIdRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
    '/_app/organisations/$organisationId/boards/$boardId': {
      id: '/_app/organisations/$organisationId/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/organisations/$organisationId/boards/$boardId'
      preLoaderRoute: typeof AppOrganisationsOrganisationIdBoardsBoardIdRouteImport
      parentRoute: typeof AppOrganisationsOrganisationIdRoute
    }
  }
}

interface AppOrganisationsOrganisationIdRouteChildren {
  AppOrganisationsOrganisationIdMembersRoute: typeof AppOrganisationsOrganisationIdMembersRoute
  AppOrganisationsOrganisationIdOverviewRoute: typeof AppOrganisationsOrganisationIdOverviewRoute
  AppOrganisationsOrganisationIdSettingsRoute: typeof AppOrganisationsOrganisationIdSettingsRoute
  AppOrganisationsOrganisationIdIndexRoute: typeof AppOrganisationsOrganisationIdIndexRoute
  AppOrganisationsOrganisationIdBoardsBoardIdRoute: typeof AppOrganisationsOrganisationIdBoardsBoardIdRoute
  AppOrganisationsOrganisationIdEventsEventIdRoute: typeof AppOrganisationsOrganisationIdEventsEventIdRoute
  AppOrganisationsOrganisationIdBoardsIndexRoute: typeof AppOrganisationsOrganisationIdBoardsIndexRoute
  AppOrganisationsOrganisationIdEventsIndexRoute: typeof AppOrganisationsOrganisationIdEventsIndexRoute
}

const AppOrganisationsOrganisationIdRouteChildren: AppOrganisationsOrganisationIdRouteChildren =
  {
    AppOrganisationsOrganisationIdMembersRoute:
      AppOrganisationsOrganisationIdMembersRoute,
    AppOrganisationsOrganisationIdOverviewRoute:
      AppOrganisationsOrganisationIdOverviewRoute,
    AppOrganisationsOrganisationIdSettingsRoute:
      AppOrganisationsOrganisationIdSettingsRoute,
    AppOrganisationsOrganisationIdIndexRoute:
      AppOrganisationsOrganisationIdIndexRoute,
    AppOrganisationsOrganisationIdBoardsBoardIdRoute:
      AppOrganisationsOrganisationIdBoardsBoardIdRoute,
    AppOrganisationsOrganisationIdEventsEventIdRoute:
      AppOrganisationsOrganisationIdEventsEventIdRoute,
    AppOrganisationsOrganisationIdBoardsIndexRoute:
      AppOrganisationsOrganisationIdBoardsIndexRoute,
    AppOrganisationsOrganisationIdEventsIndexRoute:
      AppOrganisationsOrganisationIdEventsIndexRoute,
  }

const AppOrganisationsOrganisationIdRouteWithChildren =
  AppOrganisationsOrganisationIdRoute._addFileChildren(
    AppOrganisationsOrganisationIdRouteChildren,
  )

interface AppOrganisationsRouteChildren {
  AppOrganisationsOrganisationIdRoute: typeof AppOrganisationsOrganisationIdRouteWithChildren
  AppOrganisationsIndexRoute: typeof AppOrganisationsIndexRoute
}

const AppOrganisationsRouteChildren: AppOrganisationsRouteChildren = {
  AppOrganisationsOrganisationIdRoute:
    AppOrganisationsOrganisationIdRouteWithChildren,
  AppOrganisationsIndexRoute: AppOrganisationsIndexRoute,
}

const AppOrganisationsRouteWithChildren =
  AppOrganisationsRoute._addFileChildren(AppOrganisationsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsGeneralRoute: typeof AppSettingsGeneralRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsGeneralRoute: AppSettingsGeneralRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppOrganisationsRoute: typeof AppOrganisationsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrganisationsRoute: AppOrganisationsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
